import type { Allergen } from "./types";

/**
 * Text for the vendor-facing screens (home, login, editor), in Vietnamese and English.
 * Customers' menus have their own four languages in i18n.ts. The choice is kept in a
 * cookie so server pages, server actions and API routes all answer in the same language.
 */
export type UiLang = "vi" | "en";
export const UI_COOKIE = "quan_ui";
export const pickUi = (v?: string | null): UiLang => (v === "en" ? "en" : "vi");

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en = {
  switchTo: "Tiếng Việt",
  switchLabel: "Chuyển sang tiếng Việt",

  // Home
  homeSignIn: "Sign in",
  homeOpenEditor: "Open editor",
  heroTitle: "Your menu, readable by every customer who walks past.",
  heroText: "Type your dishes or take one photo of your menu. Quán turns it into a QR sticker that shows each dish in English, Korean, Chinese and Japanese, with what's in it, what it costs in their money, and how to say it.",
  heroStart: "Make my menu",
  heroMine: "Open my menu",
  heroExample: "See an example menu",
  how: [
    ["1. Add dishes", "Type the Vietnamese names and prices. Common dishes translate themselves, or AI reads a photo of your menu."],
    ["2. Check", "Fix prices and allergens, add photos and videos. You decide what customers see."],
    ["3. Stick it up", "Print the QR sticker. Change prices any time without reprinting."],
  ] as [string, string][],
  howLabel: "How it works",

  // Account menu
  signedInAs: "Signed in as",
  myEditor: "My menu editor",
  setPassword: "Set or change password",
  newPassword: "New password (8+ characters)",
  typeAgain: "Type it again",
  savePassword: "Save password",
  saving: "Saving…",
  pwShort: "Use at least 8 characters.",
  pwMismatch: "The two passwords don't match.",
  pwSame: "That's already your password.",
  pwFailed: "Couldn't save the password. Sign out, sign in with the email link, and try again.",
  pwSaved: "Password saved. Next time, sign in with your email and password.",
  viewPublic: "View public menu ↗",
  signOut: "Sign out",
  signingOut: "Signing out…",

  // Login
  demoTitle: "Demo mode",
  demoText: "Login is off because Supabase isn't configured. Your menu is kept in this browser.",
  demoOpen: "Open the menu editor",
  loginTitle: "Sign in to your stall",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  signingIn: "Signing in…",
  orLink: "first time, or forgot your password?",
  emailLink: "Email me a sign-in link",
  sending: "Sending…",
  loginTip: "After signing in with the link, set a password from the account menu (top right) to skip the email next time.",
  sentTo: (email: string) => `We sent an email to ${email}.`,
  clickLink: "Click the link in it.",
  clickLinkMore: "This page will open your menu by itself once you're signed in, so you can keep it open.",
  orCode: "Or type the code from the email",
  signInCode: "Sign in with code",
  checking: "Checking…",
  sendAgain: "Send again",
  otherEmail: "Use a different email",
  errLinkExpired: "That sign-in link has expired or was already used, or it opened in a different browser. Send a new one below.",
  errWrongPw: "Wrong email or password. No password yet, or forgot it? Use “Email me a sign-in link” below, then set one from the account menu.",
  errTooManyTries: "Too many tries. Wait a minute and try again.",
  errSignIn: "Couldn't sign in. Try again.",
  errNeedEmail: "Enter your email first.",
  errTooManyEmails: "Too many emails sent. Wait a few minutes and try again.",
  errSendEmail: "Couldn't send the email. Check the address.",
  errNeedCode: "Enter the code from the email.",
  errBadCode: "That code didn't work. It may have expired: send a new email and use the newest code.",

  // Editor: header
  pillDemo: "Demo mode",
  pillLive: "Live",
  pillDraft: "Draft",
  pillUnsaved: "Unsaved changes",

  // Editor: step 1
  s1Title: "Your stall and menu photo",
  s1Hint: "The board on the wall, a printed sheet, or handwriting all work.",
  stallName: "Stall name",
  area: "Street / district",
  choosePhoto: "Choose a menu photo",
  choosePhotoHint: "Take a photo or pick one. JPG, PNG or WebP.",
  otherPhoto: "Choose a different photo",
  readAi: "Read menu with AI",
  reading: "Reading…",
  readAdds: "New dishes are added to your list in step 2.",
  aiOff: (n: number) => `Reading menu photos switches on once a Claude API key is added to the server. For now, type your dishes in step 2: ${n || "common"} dishes fill in their English, Korean, Chinese and Japanese names by themselves.`,
  readingWait: "Reading the menu… this usually takes 20–50 seconds.",
  photoOpenFail: "Couldn't open that photo. Try a JPG or PNG, or take a screenshot of it.",
  found: (n: number, skipped: number) => `Found ${n} ${plural(n, "dish", "dishes")}${skipped ? ` (${skipped} already on your list)` : ""}. Check them in step 2.`,

  // Editor: step 2
  s2Title: "Check dishes and prices",
  s2HintAi: "Fix anything the photo got wrong. Open a dish to correct allergens.",
  s2Hint: "Type each dish's Vietnamese name and price. Open a dish to correct allergens.",
  colDish: "Dish (Vietnamese)",
  colPrice: "Price ₫",
  colEnglish: "English",
  emptyAi: "No dishes yet. Read a photo in step 1, add one by hand, or",
  empty: "No dishes yet. Press Add a dish, or",
  loadExample: "load the example menu",
  viName: "Vietnamese name",
  priceLabel: "Price in đồng",
  needsTranslation: "Needs translation",
  mediaCount: "Photos and videos",
  edit: "Edit",
  close: "Close",
  remove: (d: string) => `Remove ${d || "dish"}`,
  englishName: "English name",
  englishPhAi: "Translate first, or type it",
  englishPh: "Type the English name",
  spice: "Spice level",
  spiceLevels: ["Not spicy", "A little", "Medium", "Very spicy"],
  sayIt: "How to say it",
  sayItPh: "e.g. fuh baw tie",
  contains: "Contains",
  media: "Photos and videos",
  addDish: "Add a dish",
  translating: "Translating…",
  translateN: (n: number) => `Translate ${n} new ${plural(n, "dish", "dishes")}`,
  checkN: (n: number) => `Check ${n} ${plural(n, "dish", "dishes")} against the list`,
  fromList: (n: number) => `${n} filled in from the built-in list. `,
  checkAllergens: "Check the allergens are right for your recipe.",
  notOnList: (n: number) => `${n} ${plural(n, "dish isn't", "dishes aren't")} on the list: open ${plural(n, "it", "each one")} with Edit and type the English name.`,
  translatingRange: (a: number, b: number, n: number) => `Translating ${a}–${b} of ${n}…`,
  translatingN: (n: number) => `Translating ${n} ${plural(n, "dish", "dishes")}…`,
  doneCheck: "Done. Check the allergens are right for your recipe.",
  keptSome: (done: number, n: number) => ` ${done} of ${n} were translated and kept; press Translate again for the rest.`,
  exampleLoaded: "Example menu loaded. Replace it with your own dishes.",

  // Editor: step 3
  s3Title: "Publish",
  s3Hint: "Customers only see the menu after you save with “Menu is live” on.",
  webAddress: "Web address",
  liveToggle: "Menu is live",
  liveToggleHint: "anyone who scans the code can see it",
  saveMenu: "Save menu",
  saved: "Saved",
  openPublic: "Open public menu ↗",
  needName: "Add your stall's name in step 1.",
  savedDemo: "Saved in this browser (demo mode).",
  couldntSave: "Couldn't save.",
  savedLive: "Saved. Your menu is live.",
  savedDraft: "Saved as a draft. Turn on “Menu is live” when you're ready.",
  saveFailed: "Couldn't save. Check your connection and try again.",

  // Editor: step 4
  s4Title: "Print the QR sticker",
  s4Hint: "Stick it on the table or the cart. Price changes show up without reprinting.",
  saveFirst: "Save your menu first to get its QR code.",
  slugChanged: "You changed the web address. Save first, or the printed code will point to the old one.",
  codeOpens: "The code opens:",
  downloadSticker: "Download sticker (PNG)",
  copyLink: "Copy link",
  copied: "Copied",
  qrFor: (url: string) => `QR code for ${url}`,
  yourStall: "Your stall",

  // Preview
  previewLabel: "Customer view preview",
  customersSee: "What customers see",
  dishCount: (n: number) => `${n} ${plural(n, "dish", "dishes")}`,

  // Dish media
  mediaDemo: "Dish photos and videos are saved to your account, so they work once logins (Supabase) are set up.",
  mediaMax: (n: number) => `Up to ${n} photos or videos per dish. Remove one first.`,
  loginExpired: "Your login expired. Sign in again.",
  uploading: "Uploading…",
  uploadingN: (k: number, n: number) => `Uploading ${k} of ${n}…`,
  badVideoType: (f: string) => `${f}: use an MP4 or MOV video.`,
  videoTooBig: (f: string, mb: number) => `${f}: videos must be under ${mb} MB (about 30 seconds).`,
  badPhoto: (f: string) => `${f}: couldn't open that photo. Try a JPG or PNG.`,
  noBucket: "Photo storage isn't set up yet: run the latest supabase/schema.sql in Supabase.",
  uploadFailed: (f: string) => `${f}: upload failed. Check your connection and try again.`,
  skippedMax: (k: number, n: number) => `${k} not added: up to ${n} per dish.`,
  added: (n: number) => `Added ${n}. Save the menu to show ${plural(n, "it", "them")} to customers.`,
  removed: "Removed. Save the menu to update it for customers.",
  addMedia: "Add photo or video",
  mediaLimits: (n: number, max: number, mb: number) => `${n}/${max} · videos up to ${mb} MB`,
  removeMedia: "Remove",

  // Server messages
  srvDemoSave: "Saving to the server needs Supabase. In demo mode your menu is kept in this browser.",
  srvNeedName: "Add your stall's name first.",
  srvShortSlug: "The web address needs at least 3 letters or numbers.",
  srvSlugTaken: (slug: string) => `The address “${slug}” is taken. Try adding your street, e.g. ${slug}-q1.`,
  srvNeedLoginsAi: "Photo reading needs vendor logins, and logins need Supabase. Add the Supabase settings to the server.",
  srvSignIn: "Sign in to use this.",
  srvAiUnavailable: "Photo reading is temporarily unavailable. Try again later.",
  srvAllowance: "You've used today's AI allowance. It resets at 7 am Vietnam time.",
  srvJson: "Send the photo as JSON.",
  srvPhotoType: "Choose a JPG, PNG or WebP photo.",
  srvPhotoBig: "That photo is too large. Try a smaller one.",
  srvNoNames: "No dish names to translate.",
  srvTooMany: "Translate at most 40 dishes at a time.",
  ai: {
    off: "Photo reading isn't set up yet: add ANTHROPIC_API_KEY to the server environment.",
    format: "The menu came back in a broken format. Try again.",
    timeout: "That took too long. Try a photo of half the menu at a time.",
    key: "Photo reading is misconfigured on the server (API key). The details are in the server logs.",
    model: "Photo reading is misconfigured on the server (model). The details are in the server logs.",
    busy: "The AI is busy right now. Wait a minute and try again.",
    down: "The AI service is having trouble. Try again in a minute.",
    conn: "Couldn't reach the AI service. Try again.",
    unknown: "Something went wrong. Try again.",
    refusal: "The AI couldn't process that. Make sure the photo shows a food menu and try again.",
    tooLong: "That menu is too long to read in one go. Photograph half at a time; new dishes are added to your list.",
    noDishes: "No dishes found in that photo. Try a clearer, straighter shot.",
  },

  allergens: {
    peanut: "Peanuts", shellfish: "Shellfish", fish: "Fish sauce", egg: "Egg", dairy: "Dairy",
    gluten: "Gluten", soy: "Soy", pork: "Pork", beef: "Beef",
  } as Record<Allergen, string>,
};

export type Strings = typeof en;
export type AiCode = keyof Strings["ai"];

const vi: Strings = {
  switchTo: "English",
  switchLabel: "Switch to English",

  homeSignIn: "Đăng nhập",
  homeOpenEditor: "Mở trình chỉnh sửa",
  heroTitle: "Thực đơn của quán, khách nước ngoài nào cũng đọc được.",
  heroText: "Gõ tên món hoặc chụp một tấm hình thực đơn. Quán biến nó thành mã QR dán bàn, hiện từng món bằng tiếng Anh, Hàn, Trung, Nhật, có thành phần, giá quy đổi ra tiền của khách và cách đọc tên món.",
  heroStart: "Làm thực đơn của tôi",
  heroMine: "Mở thực đơn của tôi",
  heroExample: "Xem thực đơn mẫu",
  how: [
    ["1. Thêm món", "Gõ tên món tiếng Việt và giá. Món phổ biến tự dịch, hoặc AI đọc hình chụp thực đơn."],
    ["2. Kiểm tra", "Sửa giá, thành phần, thêm hình và video. Bạn quyết định khách thấy gì."],
    ["3. Dán lên bàn", "In mã QR. Đổi giá bất cứ lúc nào, không cần in lại."],
  ],
  howLabel: "Cách hoạt động",

  signedInAs: "Đang đăng nhập",
  myEditor: "Chỉnh sửa thực đơn",
  setPassword: "Đặt hoặc đổi mật khẩu",
  newPassword: "Mật khẩu mới (ít nhất 8 ký tự)",
  typeAgain: "Nhập lại mật khẩu",
  savePassword: "Lưu mật khẩu",
  saving: "Đang lưu…",
  pwShort: "Mật khẩu cần ít nhất 8 ký tự.",
  pwMismatch: "Hai mật khẩu không giống nhau.",
  pwSame: "Đây đã là mật khẩu hiện tại của bạn.",
  pwFailed: "Không lưu được mật khẩu. Hãy đăng xuất, đăng nhập lại bằng link trong email rồi thử lại.",
  pwSaved: "Đã lưu mật khẩu. Lần sau đăng nhập bằng email và mật khẩu.",
  viewPublic: "Xem thực đơn công khai ↗",
  signOut: "Đăng xuất",
  signingOut: "Đang đăng xuất…",

  demoTitle: "Chế độ dùng thử",
  demoText: "Chưa bật đăng nhập vì máy chủ chưa cài Supabase. Thực đơn được lưu trên trình duyệt này.",
  demoOpen: "Mở trình chỉnh sửa thực đơn",
  loginTitle: "Đăng nhập vào quán của bạn",
  email: "Email",
  password: "Mật khẩu",
  signIn: "Đăng nhập",
  signingIn: "Đang đăng nhập…",
  orLink: "lần đầu, hoặc quên mật khẩu?",
  emailLink: "Gửi link đăng nhập qua email",
  sending: "Đang gửi…",
  loginTip: "Sau khi đăng nhập bằng link, hãy đặt mật khẩu ở menu tài khoản (góc trên bên phải) để lần sau không cần email.",
  sentTo: (email: string) => `Đã gửi email tới ${email}.`,
  clickLink: "Bấm vào link trong email.",
  clickLinkMore: "Trang này sẽ tự mở thực đơn của bạn khi đăng nhập xong, nên cứ để trang này mở.",
  orCode: "Hoặc nhập mã trong email",
  signInCode: "Đăng nhập bằng mã",
  checking: "Đang kiểm tra…",
  sendAgain: "Gửi lại",
  otherEmail: "Dùng email khác",
  errLinkExpired: "Link đăng nhập đã hết hạn, đã được dùng, hoặc đã mở ở trình duyệt khác. Hãy gửi link mới bên dưới.",
  errWrongPw: "Sai email hoặc mật khẩu. Chưa có hoặc quên mật khẩu? Bấm “Gửi link đăng nhập qua email” bên dưới, rồi đặt mật khẩu ở menu tài khoản.",
  errTooManyTries: "Thử quá nhiều lần. Đợi một phút rồi thử lại.",
  errSignIn: "Không đăng nhập được. Hãy thử lại.",
  errNeedEmail: "Hãy nhập email trước.",
  errTooManyEmails: "Đã gửi quá nhiều email. Đợi vài phút rồi thử lại.",
  errSendEmail: "Không gửi được email. Hãy kiểm tra lại địa chỉ.",
  errNeedCode: "Hãy nhập mã trong email.",
  errBadCode: "Mã không đúng hoặc đã hết hạn. Hãy gửi email mới và dùng mã mới nhất.",

  pillDemo: "Dùng thử",
  pillLive: "Đang mở",
  pillDraft: "Bản nháp",
  pillUnsaved: "Chưa lưu",

  s1Title: "Quán của bạn và hình thực đơn",
  s1Hint: "Bảng trên tường, tờ thực đơn in hay viết tay đều được.",
  stallName: "Tên quán",
  area: "Đường / quận",
  choosePhoto: "Chọn hình thực đơn",
  choosePhotoHint: "Chụp hình hoặc chọn hình có sẵn. JPG, PNG hoặc WebP.",
  otherPhoto: "Chọn hình khác",
  readAi: "Đọc thực đơn bằng AI",
  reading: "Đang đọc…",
  readAdds: "Món mới sẽ được thêm vào danh sách ở bước 2.",
  aiOff: (n: number) => `Tính năng đọc hình thực đơn sẽ mở khi máy chủ có khoá Claude API. Bây giờ, hãy gõ món ở bước 2: ${n || "các"} món phổ biến sẽ tự điền tên tiếng Anh, Hàn, Trung, Nhật.`,
  readingWait: "Đang đọc thực đơn… thường mất 20 đến 50 giây.",
  photoOpenFail: "Không mở được hình này. Hãy thử hình JPG hoặc PNG, hoặc chụp màn hình lại.",
  found: (n: number, skipped: number) => `Tìm thấy ${n} món${skipped ? ` (${skipped} món đã có trong danh sách)` : ""}. Kiểm tra lại ở bước 2.`,

  s2Title: "Kiểm tra món và giá",
  s2HintAi: "Sửa chỗ hình đọc sai. Mở từng món để chỉnh thành phần.",
  s2Hint: "Gõ tên tiếng Việt và giá của từng món. Mở từng món để chỉnh thành phần.",
  colDish: "Tên món (tiếng Việt)",
  colPrice: "Giá ₫",
  colEnglish: "Tiếng Anh",
  emptyAi: "Chưa có món nào. Đọc hình ở bước 1, thêm món bằng tay, hoặc",
  empty: "Chưa có món nào. Bấm Thêm món, hoặc",
  loadExample: "tải thực đơn mẫu",
  viName: "Tên tiếng Việt",
  priceLabel: "Giá (đồng)",
  needsTranslation: "Chưa dịch",
  mediaCount: "Hình và video",
  edit: "Sửa",
  close: "Đóng",
  remove: (d: string) => `Xoá ${d || "món"}`,
  englishName: "Tên tiếng Anh",
  englishPhAi: "Bấm dịch trước, hoặc tự gõ",
  englishPh: "Gõ tên tiếng Anh",
  spice: "Độ cay",
  spiceLevels: ["Không cay", "Hơi cay", "Cay vừa", "Rất cay"],
  sayIt: "Cách đọc (cho khách nước ngoài)",
  sayItPh: "ví dụ: fuh baw tie",
  contains: "Có chứa",
  media: "Hình và video",
  addDish: "Thêm món",
  translating: "Đang dịch…",
  translateN: (n: number) => `Dịch ${n} món mới`,
  checkN: (n: number) => `Tìm ${n} món trong danh sách có sẵn`,
  fromList: (n: number) => `Đã điền ${n} món từ danh sách có sẵn. `,
  checkAllergens: "Hãy kiểm tra thành phần có đúng với cách nấu của quán không.",
  notOnList: (n: number) => `${n} món chưa có trong danh sách: bấm Sửa ở ${n === 1 ? "món đó" : "từng món"} và gõ tên tiếng Anh.`,
  translatingRange: (a: number, b: number, n: number) => `Đang dịch món ${a}–${b} trong ${n} món…`,
  translatingN: (n: number) => `Đang dịch ${n} món…`,
  doneCheck: "Xong. Hãy kiểm tra thành phần có đúng với cách nấu của quán không.",
  keptSome: (done: number, n: number) => ` Đã dịch và giữ lại ${done}/${n} món; bấm Dịch lần nữa cho các món còn lại.`,
  exampleLoaded: "Đã tải thực đơn mẫu. Hãy thay bằng món của quán bạn.",

  s3Title: "Đăng thực đơn",
  s3Hint: "Khách chỉ thấy thực đơn sau khi bạn lưu với “Mở thực đơn” đang bật.",
  webAddress: "Địa chỉ web",
  liveToggle: "Mở thực đơn",
  liveToggleHint: "ai quét mã cũng xem được",
  saveMenu: "Lưu thực đơn",
  saved: "Đã lưu",
  openPublic: "Xem thực đơn khách thấy ↗",
  needName: "Hãy nhập tên quán ở bước 1.",
  savedDemo: "Đã lưu trên trình duyệt này (chế độ dùng thử).",
  couldntSave: "Không lưu được.",
  savedLive: "Đã lưu. Thực đơn đang mở cho khách.",
  savedDraft: "Đã lưu bản nháp. Bật “Mở thực đơn” khi sẵn sàng.",
  saveFailed: "Không lưu được. Kiểm tra kết nối mạng rồi thử lại.",

  s4Title: "In mã QR",
  s4Hint: "Dán lên bàn hoặc xe đẩy. Đổi giá thì khách thấy ngay, không cần in lại.",
  saveFirst: "Lưu thực đơn trước để có mã QR.",
  slugChanged: "Bạn đã đổi địa chỉ web. Hãy lưu trước, nếu không mã đã in sẽ mở địa chỉ cũ.",
  codeOpens: "Mã QR mở trang:",
  downloadSticker: "Tải mã QR (PNG)",
  copyLink: "Sao chép link",
  copied: "Đã sao chép",
  qrFor: (url: string) => `Mã QR mở ${url}`,
  yourStall: "Quán của bạn",

  previewLabel: "Xem trước như khách",
  customersSee: "Khách sẽ thấy",
  dishCount: (n: number) => `${n} món`,

  mediaDemo: "Hình và video của món được lưu vào tài khoản, nên chỉ dùng được khi đã cài đăng nhập (Supabase).",
  mediaMax: (n: number) => `Mỗi món tối đa ${n} hình hoặc video. Hãy xoá bớt một cái trước.`,
  loginExpired: "Phiên đăng nhập đã hết. Hãy đăng nhập lại.",
  uploading: "Đang tải lên…",
  uploadingN: (k: number, n: number) => `Đang tải lên ${k}/${n}…`,
  badVideoType: (f: string) => `${f}: hãy dùng video MP4 hoặc MOV.`,
  videoTooBig: (f: string, mb: number) => `${f}: video phải nhỏ hơn ${mb} MB (khoảng 30 giây).`,
  badPhoto: (f: string) => `${f}: không mở được hình. Hãy thử JPG hoặc PNG.`,
  noBucket: "Chưa cài nơi lưu hình: hãy chạy file supabase/schema.sql mới nhất trong Supabase.",
  uploadFailed: (f: string) => `${f}: tải lên không được. Kiểm tra mạng rồi thử lại.`,
  skippedMax: (k: number, n: number) => `${k} file chưa được thêm: mỗi món tối đa ${n}.`,
  added: (n: number) => `Đã thêm ${n}. Lưu thực đơn để khách thấy.`,
  removed: "Đã xoá. Lưu thực đơn để cập nhật cho khách.",
  addMedia: "Thêm hình hoặc video",
  mediaLimits: (n: number, max: number, mb: number) => `${n}/${max} · video tối đa ${mb} MB`,
  removeMedia: "Xoá",

  srvDemoSave: "Lưu lên máy chủ cần Supabase. Ở chế độ dùng thử, thực đơn được lưu trên trình duyệt này.",
  srvNeedName: "Hãy nhập tên quán trước.",
  srvShortSlug: "Địa chỉ web cần ít nhất 3 chữ cái hoặc số.",
  srvSlugTaken: (slug: string) => `Địa chỉ “${slug}” đã có người dùng. Thử thêm tên đường, ví dụ ${slug}-q1.`,
  srvNeedLoginsAi: "Đọc hình thực đơn cần đăng nhập, và đăng nhập cần Supabase. Hãy thêm cài đặt Supabase cho máy chủ.",
  srvSignIn: "Hãy đăng nhập để dùng tính năng này.",
  srvAiUnavailable: "Tính năng đọc hình tạm thời không dùng được. Hãy thử lại sau.",
  srvAllowance: "Bạn đã dùng hết lượt AI hôm nay. Lượt mới có lúc 7 giờ sáng giờ Việt Nam.",
  srvJson: "Hãy gửi hình dưới dạng JSON.",
  srvPhotoType: "Hãy chọn hình JPG, PNG hoặc WebP.",
  srvPhotoBig: "Hình quá lớn. Hãy thử hình nhỏ hơn.",
  srvNoNames: "Không có tên món nào để dịch.",
  srvTooMany: "Mỗi lần chỉ dịch tối đa 40 món.",
  ai: {
    off: "Chưa cài tính năng đọc hình: hãy thêm ANTHROPIC_API_KEY vào cài đặt máy chủ.",
    format: "Kết quả đọc thực đơn bị lỗi định dạng. Hãy thử lại.",
    timeout: "Đọc quá lâu. Hãy chụp từng nửa thực đơn.",
    key: "Máy chủ cài sai khoá API. Chi tiết nằm trong nhật ký máy chủ.",
    model: "Máy chủ cài sai mẫu AI. Chi tiết nằm trong nhật ký máy chủ.",
    busy: "AI đang bận. Đợi một phút rồi thử lại.",
    down: "Dịch vụ AI đang gặp sự cố. Thử lại sau một phút.",
    conn: "Không kết nối được dịch vụ AI. Hãy thử lại.",
    unknown: "Có lỗi xảy ra. Hãy thử lại.",
    refusal: "AI không xử lý được hình này. Hãy chắc chắn đó là hình thực đơn rồi thử lại.",
    tooLong: "Thực đơn quá dài để đọc một lần. Hãy chụp từng nửa; món mới sẽ được thêm vào danh sách.",
    noDishes: "Không tìm thấy món nào trong hình. Hãy chụp rõ và thẳng hơn.",
  },

  allergens: {
    peanut: "Đậu phộng", shellfish: "Tôm, cua, sò", fish: "Cá, nước mắm", egg: "Trứng", dairy: "Sữa",
    gluten: "Bột mì", soy: "Đậu nành", pork: "Thịt heo", beef: "Thịt bò",
  },
};

export const STRINGS: Record<UiLang, Strings> = { en, vi };
